ULogs.translation={}
ULogs.translation.Notify={}
if string.upper(ULogs.config.Language) == "EN" then
-- sv_ultimatelogs.lua
ULogs.translation.Name="Name"
ULogs.translation.MurderName="Murder Name"
ULogs.translation.TTTRole="TTT Role"
ULogs.translation.bystander="bystander"
ULogs.translation.Murderer="murderer"
ULogs.translation.MurderRole="Murder Role"
ULogs.translation.PHRole="PH Role"
ULogs.translation.Team="Team"
ULogs.translation.Notify.OpenMenuNotAllowed="You are not allowed to open the logs menu !"
ULogs.translation.RestrictedIP="IP : XXX.XXX.XXX.XXX (restricted)"
ULogs.translation.Notify.DeletedSuccessfully="Successfully deleted logs !"
-- ulogs_chat.lua
ULogs.translation.CopyMessage="Copy message"
ULogs.translation.Said="Said"
-- ulogs_commands.lua
ULogs.translation.Command="Command"
ULogs.translation.CopyCommand="Copy command"
ULogs.translation.Entered="Entered"
-- ulogs_connect.lua
ULogs.translation.ConnectMenu="(Dis)Connect"
ULogs.translation.Connected="Connected from the server"
ULogs.translation.Disconnected="Disconnected from the server"
-- ulogs_damage.lua
ULogs.translation.DamageKill="Damage/Kill"
ULogs.translation.Victim="Victim"
ULogs.translation.Attacker="Attacker"
ULogs.translation.Vehicle="A vehicle"
ULogs.translation.Something="Something"
ULogs.translation.FallDamage="Fall Damage"
ULogs.translation.World="The world"
ULogs.translation.Kill="[KILL]"
ULogs.translation.Killed="Killed"
ULogs.translation.With="With"
ULogs.translation.DamageUsing="Damage Using"
ULogs.translation.Hurt="[HURT]"
ULogs.translation.hurt="Hurt"
ULogs.translation.KilledHimself="Killed Himself"
-- ulogs_team.lua
ULogs.translation.Team="Team"
ULogs.translation.ChangedTeam="Changed his team from"
ULogs.translation.To="To"
elseif string.upper(ULogs.config.Language) == "FR" then
-- sv_ultimatelogs.lua
ULogs.translation.Name="Nom"
ULogs.translation.MurderName="Nom Murder"
ULogs.translation.TTTRole="Rôle TTT"
ULogs.translation.bystander="innocent"
ULogs.translation.Murderer="meurtrier"
ULogs.translation.MurderRole="Rôle Murder"
ULogs.translation.PHRole="Rôle PH"
ULogs.translation.Team="Équipe"
ULogs.translation.Notify.OpenMenuNotAllowed="Vous n'êtes pas autorisé à ouvrir le menu des logs !"
ULogs.translation.RestrictedIP="IP : XXX.XXX.XXX.XXX (restreint)"
ULogs.translation.Notify.DeletedSuccessfully="Logs supprimé !"
-- ulogs_chat.lua
ULogs.translation.CopyMessage="Copier le message"
ULogs.translation.Said="Dit"
-- ulogs_commands.lua
ULogs.translation.Command="Commande"
ULogs.translation.CopyCommand="Copier la commande"
ULogs.translation.Entered="A entré"
-- ulogs_connect.lua
ULogs.translation.ConnectMenu="(Dé)Connexion"
ULogs.translation.Connected="s'est connecté sur le serveur"
ULogs.translation.Disconnected="s'est déconnecté du serveur"
-- ulogs_damage.lua
ULogs.translation.DamageKill="Dégât/Meurtre"
ULogs.translation.Victim="Victime"
ULogs.translation.Attacker="Attaquant"
ULogs.translation.Vehicle="Un véhicule"
ULogs.translation.Something="Quelque chose"
ULogs.translation.FallDamage="Dêgat de Chute"
ULogs.translation.World="Le monde"
ULogs.translation.Kill="[MEURTRE]"
ULogs.translation.Killed="A tué"
ULogs.translation.With="Avec"
ULogs.translation.DamageUsing="De Dêgats en Utilisant"
ULogs.translation.Hurt="[BLESSURE]"
ULogs.translation.hurt="Blessé"
ULogs.translation.KilledHimself="S'est tué lui-même"
-- ulogs_team.lua
ULogs.translation.Team="Équipe"
ULogs.translation.ChangedTeam="a changé son équipe de"
ULogs.translation.To="À"
else
-- sv_ultimatelogs.lua
ULogs.translation.Name="Name"
ULogs.translation.MurderName="Murder Name"
ULogs.translation.TTTRole="TTT Role"
ULogs.translation.bystander="bystander"
ULogs.translation.Murderer="murderer"
ULogs.translation.MurderRole="Murder Role"
ULogs.translation.PHRole="PH Role"
ULogs.translation.Team="Team"
ULogs.translation.Notify.OpenMenuNotAllowed="You are not allowed to open the logs menu !"
ULogs.translation.RestrictedIP="IP : XXX.XXX.XXX.XXX (restricted)"
ULogs.translation.Notify.DeletedSuccessfully="Successfully deleted logs !"
-- ulogs_chat.lua
ULogs.translation.CopyMessage="Copy message"
ULogs.translation.Said="Said"
-- ulogs_commands.lua
ULogs.translation.Command="Command"
ULogs.translation.CopyCommand="Copy command"
ULogs.translation.Entered="Entered"
-- ulogs_connect.lua
ULogs.translation.ConnectMenu="(Dis)Connect"
ULogs.translation.Connected="Connected from the server"
ULogs.translation.Disconnected="Disconnected from the server"
-- ulogs_damage.lua
ULogs.translation.DamageKill="Damage/Kill"
ULogs.translation.Victim="Victim"
ULogs.translation.Attacker="Attacker"
ULogs.translation.Vehicle="A vehicle"
ULogs.translation.Something="Something"
ULogs.translation.FallDamage="Fall Damage"
ULogs.translation.World="The world"
ULogs.translation.Kill="[KILL]"
ULogs.translation.Killed="Killed"
ULogs.translation.With="With"
ULogs.translation.DamageUsing="Damage Using"
ULogs.translation.Hurt="[HURT]"
ULogs.translation.hurt="Hurt"
ULogs.translation.KilledHimself="Killed Himself"
-- ulogs_team.lua
ULogs.translation.Team="Team"
ULogs.translation.ChangedTeam="Changed his team from"
ULogs.translation.To="To"
end
