ULogs.translation={}
if string.upper(ULogs.config.Language) == "EN" then
-- cl_ultimatelogs.lua
ULogs.translation.Copied="Copied"
ULogs.translation.DateTime="Date / Time"
ULogs.translation.ActionLog="Action / Log"
ULogs.translation.CopyLine="Copy line"
ULogs.translation.CopyDate="Copy date"
ULogs.translation.SearchDefaultText="Search ALL Logs ..."
ULogs.translation.ChoosePlayer="Choose Player"
ULogs.translation.SelectedPlayerInvalid="Selected player is invalid"
ULogs.translation.SearchFor="Search for"
ULogs.translation.Reset="Reset"
ULogs.translation.SetPageTo="Set page to"
ULogs.translation.Tools="Tools"
ULogs.translation.Set="Set"
ULogs.translation.Cancel="Cancel"
ULogs.translation.RemoveLogs="Remove Logs"
ULogs.translation.Options="Options"
ULogs.translation.Debug="Debug"
ULogs.translation.Table="Table"
ULogs.translation.LinesPages="Lines/Pages"
ULogs.translation.TimeOut="TimeOut"
ULogs.translation.Limit="Limit"
ULogs.translation.LogsReceptionUnable="Can't receive logs data : Timed out"
ULogs.translation.Delete="Delete"
ULogs.translation.Logs="Logs"
ULogs.translation.WantDelete="Do you want to delete"
ULogs.translation.Yes="Yes"
ULogs.translation.No="No"
ULogs.translation.DeleteOldestLogs="Delete the x oldest logs"
ULogs.translation.LogsToDelete="How many logs do you want to delete ?"
ULogs.translation.Show="Show"
-- ulogs_chat.lua
ULogs.translation.CopyMessage="Copy message"
ULogs.translation.Said="Said"
-- ulogs_commands.lua
ULogs.translation.Command="Command"
ULogs.translation.CopyCommand="Copy command"
ULogs.translation.Entered="Entered"
-- ulogs_connect.lua
ULogs.translation.ConnectMenu="(Dis)Connect"
ULogs.translation.Connected="Connected from the server"
ULogs.translation.Disconnected="Disconnected from the server"
-- ulogs_damage.lua
ULogs.translation.DamageKill="Damage/Kill"
ULogs.translation.Victim="Victim"
ULogs.translation.Attacker="Attacker"
ULogs.translation.Vehicle="A vehicle"
ULogs.translation.Something="Something"
ULogs.translation.FallDamage="Fall Damage"
ULogs.translation.World="The world"
ULogs.translation.Kill="[KILL]"
ULogs.translation.Killed="Killed"
ULogs.translation.With="With"
ULogs.translation.DamageUsing="Damage Using"
ULogs.translation.Hurt="[HURT]"
ULogs.translation.hurt="Hurt"
ULogs.translation.KilledHimself="Killed Himself"
-- ulogs_team.lua
ULogs.translation.Team="Team"
ULogs.translation.ChangedTeam="Changed his team from"
ULogs.translation.To="To"
elseif string.upper(ULogs.config.Language) == "FR" then
-- cl_ultimatelogs.lua
ULogs.translation.Copied="Copié"
ULogs.translation.DateTime="Date / Heure"
ULogs.translation.ActionLog="Action / Journal"
ULogs.translation.CopyLine="Copier la ligne"
ULogs.translation.CopyDate="Copier la date"
ULogs.translation.SearchDefaultText="Chercher TOUS les Journaux ..."
ULogs.translation.ChoosePlayer="Choisir le joueur"
ULogs.translation.SelectedPlayerInvalid="Le joueur sélectionné est invalide"
ULogs.translation.SearchFor="Chercher pour"
ULogs.translation.Reset="RESET" -- Aurait pu utiliser <<Réinitialiser>> mais le boutton était trop petit pour cela.
ULogs.translation.SetPageTo="Aller vers la page"
ULogs.translation.Tools="Outils"
ULogs.translation.Set="Aller"
ULogs.translation.Cancel="Annuler"
ULogs.translation.RemoveLogs="Retirer les journaux"
ULogs.translation.Options="Options"
ULogs.translation.Debug="Debug"
ULogs.translation.Table="Table"
ULogs.translation.LinesPages="Lignes/Pages"
ULogs.translation.TimeOut="Délai d'attente"
ULogs.translation.Limit="Limite"
ULogs.translation.LogsReceptionUnable="Les données des journaux n'ont pas pu être reçu : Délai d'attente dépassé"
ULogs.translation.Delete="Supprimer"
ULogs.translation.Logs="Journaux"
ULogs.translation.WantDelete="Voulez-vous supprimer"
ULogs.translation.Yes="Oui"
ULogs.translation.No="Non"
ULogs.translation.DeleteOldestLogs="Supprimer les vieux X journaux"
ULogs.translation.LogsToDelete="Combien de journaux voulez-vous supprimer ?"
ULogs.translation.Show="Montrer les" -- ULogs a besoin d'un système de localisation beaucoup plus avancé apparament.
-- ulogs_chat.lua
ULogs.translation.CopyMessage="Copier le message"
ULogs.translation.Said="Dit"
-- ulogs_commands.lua
ULogs.translation.Command="Commande"
ULogs.translation.CopyCommand="Copier la commande"
ULogs.translation.Entered="A entré"
-- ulogs_connect.lua
ULogs.translation.ConnectMenu="(Dé)Connexion"
ULogs.translation.Connected="s'est connecté sur le serveur"
ULogs.translation.Disconnected="s'est déconnecté du serveur"
-- ulogs_damage.lua
ULogs.translation.DamageKill="Dégât/Meurtre"
ULogs.translation.Victim="Victime"
ULogs.translation.Attacker="Attaquant"
ULogs.translation.Vehicle="Un véhicule"
ULogs.translation.Something="Quelque chose"
ULogs.translation.FallDamage="Dêgat de Chute"
ULogs.translation.World="Le monde"
ULogs.translation.Kill="[MEURTRE]"
ULogs.translation.Killed="A tué"
ULogs.translation.With="Avec"
ULogs.translation.DamageUsing="De Dêgats en Utilisant"
ULogs.translation.Hurt="[BLESSURE]"
ULogs.translation.hurt="Blessé"
ULogs.translation.KilledHimself="S'est tué lui-même"
-- ulogs_team.lua
ULogs.translation.Team="Équipe"
ULogs.translation.ChangedTeam="a changé son équipe de"
ULogs.translation.To="À"
else
-- cl_ultimatelogs.lua
ULogs.translation.Copied="Copied"
ULogs.translation.DateTime="Date / Time"
ULogs.translation.ActionLog="Action / Log"
ULogs.translation.CopyLine="Copy line"
ULogs.translation.CopyDate="Copy date"
ULogs.translation.SearchDefaultText="Search ALL Logs ..."
ULogs.translation.ChoosePlayer="Choose Player"
ULogs.translation.SelectedPlayerInvalid="Selected player is invalid"
ULogs.translation.SearchFor="Search for"
ULogs.translation.Reset="Reset"
ULogs.translation.SetPageTo="Set page to"
ULogs.translation.Tools="Tools"
ULogs.translation.Set="Set"
ULogs.translation.Cancel="Cancel"
ULogs.translation.RemoveLogs="Remove Logs"
ULogs.translation.Options="Options"
ULogs.translation.Debug="Debug"
ULogs.translation.Table="Table"
ULogs.translation.LinesPages="Lines/Pages"
ULogs.translation.TimeOut="TimeOut"
ULogs.translation.Limit="Limit"
ULogs.translation.LogsReceptionUnable="Can't receive logs data : Timed out"
ULogs.translation.Delete="Delete"
ULogs.translation.Logs="Logs"
ULogs.translation.WantDelete="Do you want to delete"
ULogs.translation.Yes="Yes"
ULogs.translation.No="No"
ULogs.translation.DeleteOldestLogs="Delete the x oldest logs"
ULogs.translation.LogsToDelete="How many logs do you want to delete ?"
ULogs.translation.Show="Show"
-- ulogs_chat.lua
ULogs.translation.CopyMessage="Copy message"
ULogs.translation.Said="Said"
-- ulogs_commands.lua
ULogs.translation.Command="Command"
ULogs.translation.CopyCommand="Copy command"
ULogs.translation.Entered="Entered"
-- ulogs_connect.lua
ULogs.translation.ConnectMenu="(Dis)Connect"
ULogs.translation.Connected="Connected from the server"
ULogs.translation.Disconnected="Disconnected from the server"
-- ulogs_damage.lua
ULogs.translation.DamageKill="Damage/Kill"
ULogs.translation.Victim="Victim"
ULogs.translation.Attacker="Attacker"
ULogs.translation.Vehicle="A vehicle"
ULogs.translation.Something="Something"
ULogs.translation.FallDamage="Fall Damage"
ULogs.translation.World="The world"
ULogs.translation.Kill="[KILL]"
ULogs.translation.Killed="Killed"
ULogs.translation.With="With"
ULogs.translation.DamageUsing="Damage Using"
ULogs.translation.Hurt="[HURT]"
ULogs.translation.hurt="Hurt"
ULogs.translation.KilledHimself="Killed Himself"
-- ulogs_team.lua
ULogs.translation.Team="Team"
ULogs.translation.ChangedTeam="Changed his team from"
ULogs.translation.To="To"
end
